import "./globals.css";

export const metadata = {
  title: "My Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
     <body>
        
          <div className="min-h-screen bg-white text-black dark:bg-gray-950 dark:text-white transition-colors">
            {children}
          </div>
      </body>
    </html>
  );
}
